In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/Attrition - Attrition.csv")

In [ ]:
df.head(2)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7

In [ ]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder
from sklearn.metrics import accuracy_score

In [ ]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [ ]:
df=df.dropn()

In [ ]:
x=df.drop(columns=['Attrition'])
y=df['Attrition']

In [ ]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   BusinessTravel            1470 non-null   object
 2   DailyRate                 1470 non-null   int64
 3   Department                1470 non-null   object
 4   DistanceFromHome          1470 non-null   int64
 5   Education                 1470 non-null   int64
 6   EducationField            1470 non-null   object
 7   EmployeeCount             1470 non-null   int64
 8   EmployeeNumber            1470 non-null   int64
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1470 non-null   object
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobRole                   1470 non-null   object
 15  JobSatisfaction           1470 non-null   int64
 16  MaritalStatus             1470 non-null   object
 17  MonthlyIncome             1470 non-null   int64
 18  MonthlyRate               1470 non-null   int64
 19  NumCompaniesWorked        1470 non-null   int64
 20  Over18                    1470 non-null   object
 21  OverTime                  1470 non-null   object
 22  PercentSalaryHike         1470 non-null   int64
 23  PerformanceRating         1470 non-null   int64
 24  RelationshipSatisfaction  1470 non-null   int64
 25  StandardHours             1470 non-null   int64
 26  StockOptionLevel          1470 non-null   int64
 27  TotalWorkingYears         1470 non-null   int64
 28  TrainingTimesLastYear     1470 non-null   int64
 29  WorkLifeBalance           1470 non-null   int64
 30  YearsAtCompany            1470 non-null   int64
 31  YearsInCurrentRole        1470 non-null   int64
 32  YearsSinceLastPromotion   1470 non-null   int64
 33  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(8)
memory usage: 390.6+ KB

In [ ]:
categorical_features=['BusinessTravel','Department','EducationField','Gender',
'JobRole','MaritalStatus','Over18','OverTime']

In [ ]:
x_encoded=pd.get_dummies(x,columns=categorical_features,drop_first=True)

In [ ]:
x_encoded=x_encoded.astype(int)

In [ ]:
# x_encoded

In [ ]:
lb=LabelEncoder()

In [ ]:
y_encoded =lb.fit_transform(y)
y_encoded

array([1, 0, 1, ..., 0, 0, 0])

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x_encoded,y_encoded,test_size=0.2,random_state=42)

In [ ]:
x_train.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
1097,24,350,21,2,1,1551,3,57,2,1,...,1,0,0,0,0,0,0,0,0,0
727,18,287,5,2,1,1012,2,73,3,1,...,0,0,0,0,1,0,0,0,1,0
254,29,1247,20,2,1,349,4,45,3,2,...,0,0,0,0,0,1,0,0,0,0
1175,39,492,12,3,1,1654,4,66,3,2,...,0,0,1,0,0,0,0,1,0,0
1341,31,311,20,3,1,1881,2,89,3,2,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
sc=StandardScaler()

In [ ]:
x_train_scaled=sc.fit_transform(x_train)
x_test_scaled=sc.transform(x_test)

In [ ]:
# now we will create architecture of our model

In [ ]:
model=tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=128,activation='relu',
                          input_dim=x_train_scaled.shape[1]),  #input layer
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=64,activation='relu'),     #hidden layer
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=1,activation='sigmoid')     #output layer
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
# compile the model

In [ ]:
loss_fn=tf.keras.losses.BinaryCrossentropy()
metrics=['accuracy']

In [ ]:
learning_rate=0.001
momentum=0.9
optimizer=tf.keras.optimizers.SGD(learning_rate=learning_rate,momentum=momentum
                                  ,nesterov=True)

In [ ]:
model.compile(optimizer=optimizer,loss=loss_fn, metrics=metrics)

In [ ]:
# Train the model

In [ ]:
model.fit(x_train_scaled,
         y_train,
         epochs=50,
         batch_size=8,
         validation_split=0.1)

Epoch 1/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.6254 - loss: 0.6377 - val_accuracy: 0.7966 - val_loss: 0.5157
Epoch 2/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8100 - loss: 0.5008 - val_accuracy: 0.7966 - val_loss: 0.4868
Epoch 3/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8308 - loss: 0.4222 - val_accuracy: 0.8051 - val_loss: 0.4640
Epoch 4/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8281 - loss: 0.4271 - val_accuracy: 0.8051 - val_loss: 0.4512
Epoch 5/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8261 - loss: 0.4194 - val_accuracy: 0.8051 - val_loss: 0.4463
Epoch 6/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8365 - loss: 0.3793 - val_accuracy: 0.8136 - val_loss: 0.4342
Epoch 7/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8450 - loss: 0.3837 - val_accuracy: 0.8220 - val_loss: 0.4253
Epoch 8/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8421 - loss: 0.3614 - val_accuracy: 0.8305 - val_loss: 0.4146
Epoch 9/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8639 - loss: 0.3658 - val_accuracy: 0.8305 - val_loss: 0.4092
Epoch 10/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8633 - loss: 0.3738 - val_accuracy: 0.8390 - val_loss: 0.4061
Epoch 11/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8581 - loss: 0.3412 - val_accuracy: 0.8390 - val_loss: 0.4064
Epoch 12/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8629 - loss: 0.3354 - val_accuracy: 0.8390 - val_loss: 0.4004
Epoch 13/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8827 - loss: 0.3029 - val_accuracy: 0.8305 - val_loss: 0.3953
Epoch 14/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8709 - loss: 0.3254 - val_accuracy: 0.8220 - val_loss: 0.3967
Epoch 15/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8657 - loss: 0.3181 - val_accuracy: 0.8305 - val_loss: 0.3952
Epoch 16/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8887 - loss: 0.2758 - val_accuracy: 0.8136 - val_loss: 0.3897
Epoch 17/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8530 - loss: 0.3293 - val_accuracy: 0.8220 - val_loss: 0.3995
Epoch 18/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8791 - loss: 0.3152 - val_accuracy: 0.8136 - val_loss: 0.3972
Epoch 19/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8866 - loss: 0.3011 - val_accuracy: 0.8136 - val_loss: 0.3960
Epoch 20/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8882 - loss: 0.2886 - val_accuracy: 0.8051 - val_loss: 0.3963
Epoch 21/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8722 - loss: 0.3067 - val_accuracy: 0.8051 - val_loss: 0.3966
Epoch 22/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8955 - loss: 0.2803 - val_accuracy: 0.8051 - val_loss: 0.3971
Epoch 23/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8860 - loss: 0.2885 - val_accuracy: 0.8051 - val_loss: 0.3992
Epoch 24/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8850 - loss: 0.2742 - val_accuracy: 0.8136 - val_loss: 0.4022
Epoch 25/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8824 - loss: 0.2669 - val_accuracy: 0.8220 - val_loss: 0.4054
Epoch 26/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8838 - loss: 0.2663 - val_accuracy: 0.8136 - val_loss: 0.4094
Epoch 27/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8998 - loss: 0.2408 - val_accuracy: 0.8051 - val_loss: 0.4101
Epoch 28/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9011 - loss: 0.2482 - val_accuracy: 0.8051 - val_loss: 0.4123
Epoch 29/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8801 - loss: 0.2803 - val_accuracy: 0.8051 - val_loss: 0.4173
Epoch 30/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8937 - loss: 0.2765 - val_accuracy: 0.8051 - val_loss: 0.4195
Epoch 31/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9021 - loss: 0.2447 - val_accuracy: 0.8051 - val_loss: 0.4121
Epoch 32/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8958 - loss: 0.2478 - val_accuracy: 0.8051 - val_loss: 0.4216
Epoch 33/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9167 - loss: 0.2228 - val_accuracy: 0.8051 - val_loss: 0.4224
Epoch 34/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9064 - loss: 0.2304 - val_accuracy: 0.8051 - val_loss: 0.4199
Epoch 35/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8990 - loss: 0.2403 - val_accuracy: 0.8051 - val_loss: 0.4169
Epoch 36/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9055 - loss: 0.2307 - val_accuracy: 0.7966 - val_loss: 0.4204
Epoch 37/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9180 - loss: 0.2284 - val_accuracy: 0.8051 - val_loss: 0.4251
Epoch 38/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8971 - loss: 0.2554 - val_accuracy: 0.8136 - val_loss: 0.4347
Epoch 39/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8920 - loss: 0.2398 - val_accuracy: 0.7966 - val_loss: 0.4250
Epoch 40/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9107 - loss: 0.2152 - val_accuracy: 0.8136 - val_loss: 0.4351
Epoch 41/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9290 - loss: 0.2031 - val_accuracy: 0.8136 - val_loss: 0.4321
Epoch 42/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9291 - loss: 0.1915 - val_accuracy: 0.8136 - val_loss: 0.4391
Epoch 43/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9105 - loss: 0.2093 - val_accuracy: 0.8136 - val_loss: 0.4423
Epoch 44/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9038 - loss: 0.2015 - val_accuracy: 0.8136 - val_loss: 0.4411
Epoch 45/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9181 - loss: 0.2028 - val_accuracy: 0.8136 - val_loss: 0.4382
Epoch 46/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9175 - loss: 0.2124 - val_accuracy: 0.8136 - val_loss: 0.4468
Epoch 47/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9074 - loss: 0.2092 - val_accuracy: 0.8136 - val_loss: 0.4425
Epoch 48/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9146 - loss: 0.2020 - val_accuracy: 0.8220 - val_loss: 0.4459
Epoch 49/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9148 - loss: 0.2108 - val_accuracy: 0.8136 - val_loss: 0.4484
Epoch 50/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9192 - loss: 0.1812 - val_accuracy: 0.8136 - val_loss: 0.4534

In [ ]:
loss , accuracy =model.evaluate(x_test_scaled,y_test)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8825 - loss: 0.3595

In [ ]:
print(f'Test Loss={loss:.4f},Test Accuracy={accuracy:.4f}')

Test Loss=0.3487,Test Accuracy=0.8810

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder
from sklearn.metrics import accuracy_score

In [ ]:
df=pd.read_csv("/content/titanic - titanic.csv")

In [ ]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S

In [ ]:

df=df.drop(columns=['Name','PassengerId','Ticket','Cabin'])

In [ ]:
df.isnull().sum()

Survived     0
Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [ ]:
df['Age']=df['Age'].fillna(df['Age'].mean())
df['Fare']=df['Fare'].fillna(df['Fare'].mean())

In [ ]:
df.dtypes

Survived      int64
Pclass        int64
Sex          object
Age         float64
SibSp         int64
Parch         int64
Fare        float64
Embarked     object
dtype: object

In [ ]:
lb=LabelEncoder()

In [ ]:
df['Sex']=lb.fit_transform(df['Sex'])
df['Embarked']=lb.fit_transform(df['Embarked'])

In [ ]:
sc=StandardScaler()

In [ ]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [ ]:
from imblearn.over_sampling import SMOTE

smote=SMOTE(sampling_strategy='minority')
x,y=smote.fit_resample(x,y)
y.value_counts()

Survived
0    266
1    266
Name: count, dtype: int64

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_train_scaled=sc.fit_transform(x_train)
x_test_scaled=sc.transform(x_test)

In [ ]:
model=tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=128,activation='relu',
                          input_dim=x_train_scaled.shape[1]),  #input layer
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=64,activation='relu'),     #hidden layer
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=1,activation='sigmoid')     #output layer
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
loss_fn=tf.keras.losses.BinaryCrossentropy()
metrics=['accuracy']

In [ ]:
learning_rate=0.001
momentum=0.9
optimizer=tf.keras.optimizers.SGD(learning_rate=learning_rate,momentum=momentum
                                  ,nesterov=True)

In [ ]:
model.compile(optimizer=optimizer,loss=loss_fn, metrics=metrics)

In [ ]:
model.fit(x_train_scaled,
         y_train,
         epochs=50,
         batch_size=8,
         validation_split=0.1)

Epoch 1/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.4112 - loss: 0.7465 - val_accuracy: 0.8837 - val_loss: 0.6462
Epoch 2/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7250 - loss: 0.6351 - val_accuracy: 0.9302 - val_loss: 0.5586
Epoch 3/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8689 - loss: 0.5476 - val_accuracy: 0.9535 - val_loss: 0.4718
Epoch 4/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9224 - loss: 0.4726 - val_accuracy: 0.9767 - val_loss: 0.3869
Epoch 5/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9506 - loss: 0.3880 - val_accuracy: 1.0000 - val_loss: 0.3076
Epoch 6/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9715 - loss: 0.3019 - val_accuracy: 1.0000 - val_loss: 0.2370
Epoch 7/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9916 - loss: 0.2223 - val_accuracy: 1.0000 - val_loss: 0.1811
Epoch 8/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9893 - loss: 0.1749 - val_accuracy: 1.0000 - val_loss: 0.1374
Epoch 9/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.9859 - loss: 0.1523 - val_accuracy: 1.0000 - val_loss: 0.1054
Epoch 10/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9969 - loss: 0.1178 - val_accuracy: 1.0000 - val_loss: 0.0822
Epoch 11/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9987 - loss: 0.1053 - val_accuracy: 1.0000 - val_loss: 0.0650
Epoch 12/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0760 - val_accuracy: 1.0000 - val_loss: 0.0530
Epoch 13/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9963 - loss: 0.0699 - val_accuracy: 1.0000 - val_loss: 0.0433
Epoch 14/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9958 - loss: 0.0688 - val_accuracy: 1.0000 - val_loss: 0.0358
Epoch 15/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9982 - loss: 0.0482 - val_accuracy: 1.0000 - val_loss: 0.0302
Epoch 16/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9930 - loss: 0.0555 - val_accuracy: 1.0000 - val_loss: 0.0256
Epoch 17/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0373 - val_accuracy: 1.0000 - val_loss: 0.0222
Epoch 18/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9995 - loss: 0.0358 - val_accuracy: 1.0000 - val_loss: 0.0195
Epoch 19/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0300 - val_accuracy: 1.0000 - val_loss: 0.0171
Epoch 20/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9995 - loss: 0.0318 - val_accuracy: 1.0000 - val_loss: 0.0151
Epoch 21/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9998 - loss: 0.0267 - val_accuracy: 1.0000 - val_loss: 0.0134
Epoch 22/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0225 - val_accuracy: 1.0000 - val_loss: 0.0120
Epoch 23/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9992 - loss: 0.0198 - val_accuracy: 1.0000 - val_loss: 0.0108
Epoch 24/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0189 - val_accuracy: 1.0000 - val_loss: 0.0099
Epoch 25/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0146 - val_accuracy: 1.0000 - val_loss: 0.0091
Epoch 26/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0161 - val_accuracy: 1.0000 - val_loss: 0.0083
Epoch 27/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0198 - val_accuracy: 1.0000 - val_loss: 0.0075
Epoch 28/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9886 - loss: 0.0276 - val_accuracy: 1.0000 - val_loss: 0.0069
Epoch 29/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0149 - val_accuracy: 1.0000 - val_loss: 0.0064
Epoch 30/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0144 - val_accuracy: 1.0000 - val_loss: 0.0059
Epoch 31/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0131 - val_accuracy: 1.0000 - val_loss: 0.0055
Epoch 32/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0153 - val_accuracy: 1.0000 - val_loss: 0.0051
Epoch 33/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0123 - val_accuracy: 1.0000 - val_loss: 0.0047
Epoch 34/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9993 - loss: 0.0191 - val_accuracy: 1.0000 - val_loss: 0.0044
Epoch 35/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0100 - val_accuracy: 1.0000 - val_loss: 0.0042
Epoch 36/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0102 - val_accuracy: 1.0000 - val_loss: 0.0039
Epoch 37/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 1.0000 - loss: 0.0093 - val_accuracy: 1.0000 - val_loss: 0.0037
Epoch 38/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9963 - loss: 0.0155 - val_accuracy: 1.0000 - val_loss: 0.0035
Epoch 39/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0092 - val_accuracy: 1.0000 - val_loss: 0.0033
Epoch 40/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0072 - val_accuracy: 1.0000 - val_loss: 0.0031
Epoch 41/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0096 - val_accuracy: 1.0000 - val_loss: 0.0030
Epoch 42/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0109 - val_accuracy: 1.0000 - val_loss: 0.0028
Epoch 43/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9994 - loss: 0.0075 - val_accuracy: 1.0000 - val_loss: 0.0026
Epoch 44/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9948 - loss: 0.0110 - val_accuracy: 1.0000 - val_loss: 0.0025
Epoch 45/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0048 - val_accuracy: 1.0000 - val_loss: 0.0024
Epoch 46/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0087 - val_accuracy: 1.0000 - val_loss: 0.0023
Epoch 47/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0083 - val_accuracy: 1.0000 - val_loss: 0.0022
Epoch 48/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0081 - val_accuracy: 1.0000 - val_loss: 0.0021
Epoch 49/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 1.0000 - loss: 0.0062 - val_accuracy: 1.0000 - val_loss: 0.0020
Epoch 50/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0067 - val_accuracy: 1.0000 - val_loss: 0.0019

In [ ]:
loss , accuracy =model.evaluate(x_test_scaled,y_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 0.0015

In [ ]:
print(f'Test Loss={loss:.4f},Test Accuracy={accuracy:.4f}')

Test Loss=0.0016,Test Accuracy=1.0000